### ISSUE TITLE
pdbx_poly_seq_scheme

### ISSUE THREAD

**Issue by brindakv** [salilab/modbase_utils#1]
`modbase_pdb_to_cif.py` does not output `pdbx_poly_seq_scheme` table.

**Comment by benmwebb** [comment]
This should be easy enough to add since we already provide `label_seq_id` and `auth_seq_id` for `_atom_site`. Any data items that you absolutely need for your application, or do you just need the table itself (with all keys of course) to exist?

**Comment by brindakv** [comment]
The table is needed to cover all the parent-child dependencies.
